publish_to: none

name: passkeys_server_relic_example
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/LunaONE/passkeys_server
homepage: https://passkeys-server.lunaone.de/

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  cbor: ^6.3.5
  passkeys_server: ^1.0.0
  passkeys_server_relic: ^1.0.0
  relic: ^0.6.0
  uuid: ^4.5.1

dev_dependencies:
  lints: ">=3.0.0 <7.0.0"
  test: ^1.24.0

dependency_overrides:
  passkeys_server:
    path: ../passkeys_server
  passkeys_server_relic:
    path: ../passkeys_server_relic
