name: passkeys_server_relic
description: A sample command-line application.
version: 0.1.0
repository: https://github.com/LunaONE/passkeys_server

publish_to: none

environment:
  sdk: ^3.5.4

dependencies:
  dart_jsonwebtoken: ^3.0.0
  relic: ^0.4.0
  uuid: ^4.0.0
  passkeys_server: ^1.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

dependency_overrides:
  passkeys_server:
    path: ../passkeys_server
