publish_to: none

name: passkeys_server_relic_example
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/LunaONE/passkeys_server

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  relic: ^0.4.0
  passkeys_server: ^1.0.0
  passkeys_server_relic: ^1.0.0

dev_dependencies:
  lints: ">=3.0.0 <7.0.0"
  test: ^1.24.0

dependency_overrides:
  passkeys_server:
    path: ../../passkeys_server
  passkeys_server_relic:
    path: ../
